server:
  port: 8085
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 492440223300-nf4k9p52apge451acm20v4euaseotc78.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 523653339636439
            client-secret: fcf22c339160fb67b190c6cb1c147104
            scope:
            - email
            - public_profile

          naver:
            client-id: b2XdcaYhym8nXFPCv2_h
            client-secret: GigAIEAsig
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/login/oauth2/code/naver #로그인 후 이동할 주소

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize  #로그인창 호출
            token-uri: https://nid.naver.com/oauth2.0/token  #토큰 호출
            user-info-uri: https://openapi.naver.com/v1/nid/me  #회원정보 호출
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
